# See dos how to configure the bundle: https://symfony.com/doc/current/bundles/LiipImagineBundle/basic-usage.html
liip_imagine:
    # valid drivers options include "gd" or "gmagick" or "imagick"
    driver: "gd"
    filter_sets:
        vignettes:
            quality: 75
            filters:
                scale:
                    dim: [50, 50]
        article:
            quality: 80
            filters: 
                upscale:
                    min: [700, 300]
                thumbnail:
                    size: [700, 300]
                    mode: inset

